name: Build
 
on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - uses: actions/cache@v2
         with:
           path: node_modules
           key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
           restore-keys: |
             ${{ runner.os }}-npm-
       - uses: actions/setup-node@v2
         with:
           node-version: '14'
       - name: Install Dependencies
         run: npm install
       - name: Run Linter
         run: npm run lint
       
  deploy:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
       - name: Deploy to dokku
         id: deploy
         uses: idoberko2/dokku-deploy-github-action@v1
         with:
           ssh-private-key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
           dokku-host: '78.47.176.210'
           app-name: 'dogtor-backend'
           git-push-flags: --force
