name: CI
 
on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - uses: actions/cache@v2
         with:
           path: node_modules
           key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
           restore-keys: |
             ${{ runner.os }}-npm-
       - uses: actions/setup-node@v2
         with:
           node-version: '14'
       - name: Install Dependencies
         run: npm install
       - name: Run Linter
         run: npm run lint
         
  build:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
       - uses: actions/checkout@v2
       - uses: actions/cache@v2
         with:
           path: node_modules
           key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
           restore-keys: |
             ${{ runner.os }}-npm-
       - uses: actions/setup-node@v2
         with:
           node-version: '14'
       - name: Install Dependencies
         run: npm install
       - name: Build for Production
         run: npm run build
