name: Deploy Staging

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/stage'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Get Pull Request Ref
        id: get_pull_request_ref
        uses: octokit/request-action@v2.x
        if: steps.check.outputs.triggered == 'true'
        with:
          route: GET /repos/:repository/pulls/:issue_id
          repository: ${{ github.repository }}
          issue_id: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Deploy to dokku
        if: steps.check.outputs.triggered == 'true'
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:Dogtor-Assistant/backend.git"
          source_branch: ${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}
          destination_repo: "dokku@78.47.176.210:dogtor-backend-staging"
          destination_branch: "master"
          source_ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          destination_ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
      - name: Comment PR
        if: steps.check.outputs.triggered == 'true'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ':rocket: Deployed to Staging: https://staging.backend.dogtor.xyz'
